In [32]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [33]:
env = gym.make("FrozenLake-v0")

In [34]:
action_space_size =env.action_space.n
state_space_size =env.observation_space.n
q_table =  np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate  = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [36]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold>exploration_rate:
            action = np.argmax(q_table[state,:])
        else:    
            action = env.action_space.sample()
            
        new_state,reward,done,info = env.step(action)
       
        q_table[state,action] = q_table[state,action]*(1-learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, : ]))
        
        state = new_state
        
        rewards_current_episode += reward
        
        if done == True:
            break
        
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) *np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
    
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("******************Average return per thousand episodes****************\n")

for r in rewards_per_thousand_episodes:
        print(count,": ",str(sum(r/1000)))
        count += 1000
        



******************Average return per thousand episodes****************

1000 :  0.046000000000000034
2000 :  0.20200000000000015
3000 :  0.4090000000000003
4000 :  0.5540000000000004
5000 :  0.6120000000000004
6000 :  0.6380000000000005
7000 :  0.6730000000000005
8000 :  0.6880000000000005
9000 :  0.6760000000000005
10000 :  0.6770000000000005


In [37]:
print("******************Q - Table****************\n")
print(q_table)

******************Q - Table****************

[[0.54910022 0.49536634 0.50099833 0.46471882]
 [0.36212663 0.1603826  0.25277604 0.47664557]
 [0.40574788 0.3016345  0.30183519 0.27344322]
 [0.14161334 0.08136378 0.00940949 0.09076621]
 [0.56498632 0.33264654 0.39536855 0.28365522]
 [0.         0.         0.         0.        ]
 [0.30151037 0.1295631  0.16138902 0.13512317]
 [0.         0.         0.         0.        ]
 [0.32803975 0.34789805 0.35872045 0.59389924]
 [0.56751365 0.61117587 0.55760502 0.39310128]
 [0.50868753 0.36462527 0.34729697 0.25484164]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.46698043 0.41566864 0.74554941 0.3850783 ]
 [0.73563884 0.82495938 0.84703983 0.7575521 ]
 [0.         0.         0.         0.        ]]


In [38]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*******EPISODE ",episode+1,"****************\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(q_table[state, :])
        new_state,reward,done,info = env.step(action)
        
        
        if done:
            clear_output(wait = True)
            env.render()
            if(reward == 1):
                print("*********You reached the goal***************\n")
                time.sleep(3)
            else:
                print("*********You fell through a hole***************\n")
                time.sleep(3)
            clear_output(wait = True)
            break
            
        state = new_state
        
env.close()
        

  (Right)
SFFF
FHFH
FFFH
HFFG
*********You reached the goal***************

